name = "cf-worker-hono-template"
main="src/index.ts"

compatibility_date = "2024-05-19"
workers_dev = true
upload_source_maps = true

[dev]
port = 8787

[env.dev]
vars = { ENVIRONMENT = "dev" }

[env.production]
vars = { ENVIRONMENT = "prod" }
